### ISSUE TITLE
VPA patches the deployment instead of individual pods

### ISSUE THREAD

**Issue by harpratap** [mercari/tortoise#104]
I think by default VPA should patch the deployment.spec for requests instead of pod.spec

This ensures that any other pod from the replicaset can also handle if uneven spike happens on it. Also, replicasets are recreated, so these new VPA recommended values should persist across pod creation

This is highly depended on controller type though, for eg. daemonsets and statefulsets should not apply the same changes across all pods

**Comment by sanposhiho** [comment]
We talked in slack and I believe we can close it for now. The actual issue behind this issue is kind of a special case due to `minAllowed`. (In case of tortoise, VPA won't get any `minAllowed` so such problems shouldn't happen.)
Let's reopen if we find any other problems which can be solved by this.
